# CHANGE ME
project_root_dir: /home/owen/workspace/visual-questioner

checkpoint_path: im2txt/model.ckpt-2000000
vocab_file_path: im2txt/word_counts.txt

preprocess:
  lowercase: True
  punctuation_spaces: False
  only_ending_spaces: True
  no_punctuation_spaces_for_questions: False

drop_non_ascii: True
drop_punctuated_questions: True
